name: Deploy Sales Service

on:
  push:
    branches:
      - main
    paths:
      - 'sales/**'

deploy_sales:
    runs-on: ubuntu-latest

    env:
      SALES_ENV_VAR_1: ${{ secrets.SALES_ENV_VAR_1}}
      SALES_ENV_VAR_2: ${{ secrets.SALES_ENV_VAR_2}}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.11

    - name: Deploy sales subfolder
      run: |
        echo "Deploying contents of sales subfolder..."
        # Add your deployment script or commands for the 'sales/' subfolder here
        echo "Sales Environment Variable 1: $SALES_ENV_VAR_1"
        echo "Sales Environment Variable 2: $SALES_ENV_VAR_2"
        cd sales/
        python sales_api.py